package com.kingg.api_vacunas_panama.util;

public enum ApiResponseCode {
    NOT_FOUND,
    VALIDATION_FAILED,
    COMPROMISED_PASSWORD,
    MISSING_INFORMATION,
    NAME_IGNORED_FOR_ID,
    ALREADY_IN_USE,
    ALREADY_EXISTS,
    ALREADY_TAKEN,
    PERMISSION_DENIED,
    INSUFFICIENT_ROLE_PRIVILEGES,
    MISSING_ROLE_OR_PERMISSION,
    INVALID_PERMISSION_OPERATION,
    ROL_HIERARCHY_VIOLATION,
    INFORMATION_IGNORED,
    API_UPDATE_UNSUPPORTED,
    NON_IDEMPOTENCE
}
