package com.kingg.api_vacunas_panama.util;

public enum CategoriaType {
    MEDICINA_GENERAL,
    ANESTESIOLOGIA,
    CARDIOLOGIA,
    DERMATOLOGIA,
    GASTROENTEROLOGIA,
    GERIATRIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    INFECTOLOGIA,
    NEFROLOGIA,
    NEUMOLOGIA,
    NEUROLOGIA,
    OBSTETRICIA,
    OFTALMOLOGIA,
    ONCOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    RADIOLOGIA,
    REUMATOLOGIA,
    TRAUMATOLOGIA,
    UROLOGIA
}
